apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: port
    port: 2379
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
subsets:
- addresses:
  - ip: 192.168.19.16
    nodeName: etcd-master1
  - ip: 192.168.19.17
    nodeName: etcd-master2
  - ip: 192.168.19.18
    nodeName: etcd-master3
  ports:
  - name: port
    port: 2379
    protocol: TCP